version: '3.1'

services:
  db:
    image: postgres:15
    container_name: book_postgres
    restart: always
    environment:
      POSTGRES_DB: book_db
      POSTGRES_USER: book_user
      POSTGRES_PASSWORD: book_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
